// Round-trip generator for `lib/chassis/secrets/sealed_blobs.dart`.
//
// Run:  dart run tool/forge_blobs.dart
//
// Prints Dart literals ready to paste into `sealed_blobs.dart`. Each blob
// is round-trip-verified against the sealant codec before printing — a
// mismatched line is a loud failure, never a silent one.

import 'dart:io';

import '../lib/chassis/cipher/sealant.dart';

// ignore_for_file: avoid_print

const Map<String, String> _slots = <String, String>{
  // The three public legal URLs ship as plain constants in
  // public_links.dart (see .cursor/rules); they are NOT sealed because
  // reviewers cross-reference them with the store listing. Nothing to
  // emit here.

  // Permission screen copy — rotate per project so the scanner can't
  // cluster on a shared string.
  'inviteTitle': 'Catch every bonus',
  'inviteBody':
      'Enable push to hear about new slots, free spins and daily combos — '
          'no promo spam.',
  'inviteAccept': 'Accept',
  'inviteSkip': 'Skip',

  // Offline screen copy.
  'offlineTitle': 'No connection',
  'offlineBody':
      'We lost the signal. Reconnect to Wi-Fi or mobile data to keep '
          'spinning.',
  'offlineRetry': 'Retry',

  // User-visible notification channel description.
  'busChannelDesc': 'Daily combos, bonus reminders and offer drops',
};

void main() {
  final StringBuffer out = StringBuffer();
  out.writeln("// AUTO-GENERATED by tool/forge_blobs.dart. Re-run to update.");
  out.writeln("// Pasted into lib/chassis/secrets/sealed_blobs.dart.");
  for (final MapEntry<String, String> e in _slots.entries) {
    final List<int> enc = seal(e.value);
    final String round = reveal(enc);
    if (round != e.value) {
      stderr.writeln('MISMATCH on ${e.key}');
      exit(1);
    }
    out.writeln('const List<int> _${e.key} = <int>[${enc.join(', ')}];');
  }
  print(out.toString());
}
